project_id: "597587"
api_token_env: "CROWDIN_PERSONAL_TOKEN"
base_path: "."
commit_message: "feat: New translations %original_file_name% from Crowdin"

files:
  - source: app/**/res/values/strings.xml
    translation: app/**/res/values-%android_code%/strings.xml
    languages_mapping:
      android_code:
        zh-rCN: "zh"
        ru-rRU: "ru"
        it-rIT: "it"
        es-rES: "es"
        fr-rFR: "fr"
        pt-rPT: "pt"
        de-rDE: "de"
        ja-rJP: "ja"
        ko-rKR: "ko"

  - source: app/**/res/values/languages.xml
    translation: app/**/res/values-%android_code%/languages.xml
    languages_mapping:
      android_code:
        zh-rCN: "zh"
        ru-rRU: "ru"
        it-rIT: "it"
        es-rES: "es"
        fr-rFR: "fr"
        pt-rPT: "pt"
        de-rDE: "de"
        ja-rJP: "ja"
        ko-rKR: "ko"
