[versions]
kotlin = "1.5.30"

[libraries]
android-gradle = "com.android.tools.build:gradle:7.0.3"
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinx-coroutines-core = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.4.1"
androidx-appcompat = "androidx.appcompat:appcompat:1.3.1"
androidx-recyclerview = "androidx.recyclerview:recyclerview:1.2.1"
androidx-dynamicanimation = "androidx.dynamicanimation:dynamicanimation:1.0.0"
androidx-annotation = "androidx.annotation:annotation:1.2.0"
androidx-core-ktx = "androidx.core:core-ktx:1.6.0"
androidx-preference-ktx = "androidx.preference:preference-ktx:1.1.1"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.0.4"
androidx-browser = "androidx.browser:browser:1.3.0"
google-browserhelper = "com.google.androidbrowserhelper:androidbrowserhelper:2.2.0"
google-material = "com.google.android.material:material:1.4.0"

free-reflection = "me.weishu:free_reflection:3.0.1"

leakcanary = "com.squareup.leakcanary:leakcanary-android:2.7"

junit = "junit:junit:4.13.2"
androidx-junit = "androidx.test.ext:junit:1.1.3"
androidx-expresso-core = "androidx.test.espresso:espresso-core:3.4.0"

[bundles]
classpath = ["android-gradle", "kotlin-gradle"]
android-test = ["androidx-junit", "androidx-expresso-core"]
