name: Android Build Release CI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true

    - name: Set up Fastlane
      run: |
        bundle install 
        bundle exec fastlane install_plugins

    - name: Retrieve the secret and decode it to a file
      env:
        KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        KEY_PROPERTIES_BASE64: ${{ secrets.KEY_PROPERTIES_BASE64 }}
        JSON_KEY_FILE_BASE64: ${{ secrets.JSON_KEY_FILE_BASE64 }}
      run: |
        echo "$KEY_PROPERTIES_BASE64" | base64 --decode > key.properties
        echo "$KEYSTORE_BASE64" | base64 --decode > keystore.jks
        echo "$JSON_KEY_FILE_BASE64" | base64 --decode > json_key_file.json

    - name: Deploy to the Google Play
      env:
        JSON_KEY_FILE: 'json_key_file.json'
      run: bundle exec fastlane deploy

    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew clean app:assembleRelease

    - name: Get Change logs
      id: get-change-logs
      run: |
        CHANGE_LOGS=`ls -r fastlane/metadata/android/en-US/changelogs | head -1`
        echo "CHANGE_LOGS=$CHANGE_LOGS" >> "$GITHUB_OUTPUT"

    - name: Create Github Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: false
        prerelease: false
        bodyFile: fastlane/metadata/android/en-US/changelogs/${{ steps.get-change-logs.outputs.CHANGE_LOGS }}
        artifacts: ./app/build/outputs/apk/release/*.apk
        artifactContentType: application/vnd.android.package-archive
        allowUpdates: true
        updateOnlyUnreleased: true
