name: Crowdin Upload Action

on:
  push:
    paths:
      - 'app/**/res/values/strings.xml'
      - 'app/**/res/values/languages.xml'
    branches: [ master ]
  workflow_dispatch:

jobs:
  crowdin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Crowdin push
        uses: crowdin/github-action@v1
        with:
          config: '.github/crowdin.yml'
          upload_sources: true
          upload_translations: false
          download_translations: false
        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
