name: Crowdin Synchronize Action

on:
  push:
    paths:
      - 'app/src/main/res/values*/strings.xml'
      - 'app/src/main/res/values*/languages.xml'
      - 'app/src/main/res/values*/strings*.xml'
    branches: [ main ]
  schedule:
    - cron: '0 1 * * 0'
  workflow_dispatch:

jobs:
  crowdin:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies

      - name: Synchronize with Crowdin
        uses: crowdin/github-action@v1
        id: crowdin
        with:
          upload_sources: true
          upload_translations: true
          download_translations: true

          create_pull_request: true
          localization_branch_name: l10n_crowdin_translations
          pull_request_title: 'feat: New Crowdin translations'
          pull_request_base_branch_name: 'main'
          pull_request_labels: 'translations, enhancement'
          pull_request_assignees: 'crowdin-bot'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Update Crowdin project progress
        run: |
          cd script/crowdin
          pip install -r requirements.txt
          python start.py ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Commit Crowdin project progress svg
        uses: EndBug/add-and-commit@v9
        with:
          new_branch: l10n_crowdin_translations
          pull: '--rebase'
          message: "feat: Update Crowdin project progress"
          add: '*.svg'

      - name: Enable auto-merge for the PR
        if: steps.crowdin.outputs.pull_request_url
        run: gh pr --repo $GITHUB_REPOSITORY merge ${{ steps.crowdin-download.outputs.pull_request_url }} --auto --merge --delete-branch
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}